#!/bin/sh

. /etc/profile

URL="http://admin@localhost/rest/apps"
PKG="50_zxing-core.jar 50_zxing-javase.jar 40_@Bundle-SymbolicName@.jar"

for pkg in $PKG; do
  busybox wget $URL/$pkg/plug -q --spider
done

exit 0